apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api-main
  labels:
    app: user-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-api
  template:
    metadata:
      labels:
        app: user-api
    spec:
      containers:
        - name: user-api-pod
          image: supertacr.azurecr.io/user-api:v6
          imagePullPolicy: Always
          ports:
            - containerPort: 7770
          env:
            - name: dbUrl
              valueFrom:
                configMapKeyRef:
                  name: db-configmap
                  key: db_url
            - name: dbUser
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-root-username
            - name: dbPwd
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-root-password
            - name: secretOrKey
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: secret-or-key
---
apiVersion: v1
kind: Service
metadata:
  name: user-api-svc
spec:
  selector:
    app: user-api
  ports:
    - name: user-api-port
      protocol: TCP
      port: 80
      targetPort: 7770
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: user-api-ext-svc
# spec:
#   type: LoadBalancer
#   selector:
#     app: user-api
#   ports:
#     - name: user-api-port
#       protocol: TCP
#       port: 80
#       targetPort: 7770
